apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: namenode
  labels:
    k8s-app: namenode
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: namenode
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "k8s-app"
                    operator: In
                    values:
                    - namenode
              topologyKey: "kubernetes.io/hostname"
      hostNetwork: true
      containers:
      - image: 10.2.1.227:5000/test/hdfs:standalone-2.6.5
        name: namenode
        command:
        - sh
        - -c
        -  /check_format.sh && $HADOOP_PRFIX/bin/hdfs --config $HADOOP_PRFIX/etc/hadoop namenode
        resources:
          limits:
            cpu: 500m
        ports:
        - containerPort: 50070
          name: http-port
        - containerPort: 9000
          name: rpc-port
        env:
        - name: "HADOOP_PRFIX"
          value: "/opt/hadoop-2.6.5"
        - name: "HDFS_TMP_DIR"
          value: "/opt/hdfs/tmp"
        volumeMounts:
        - name: hdfs-core-cfg
          mountPath: /opt/hadoop-2.6.5/etc/hadoop/core-site.xml
          subPath: core-site.xml
        - name: hdfs-site-cfg
          mountPath: /opt/hadoop-2.6.5/etc/hadoop/hdfs-site.xml
          subPath: hdfs-site.xml
      volumes:
        - name: hdfs-core-cfg
          configMap:
            name: hdfs-cfg
        - name: hdfs-site-cfg
          configMap:
            name: hdfs-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: namenode
  labels:
    k8s-app: namenode
spec:
  ports:
  - port: 50070
    protocol: TCP
    name: http-port
  - port: 9000
    protocol: TCP
    name: rpc-port
  clusterIP: None
  selector:
    k8s-app: namenode
