apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: datanode
spec:
  template:
    metadata:
      labels:
        k8s-app: datanode
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/hdfs-ds-ready: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - image: 10.2.1.227:5000/test/hdfs:2.6.5
        name: datanode
        command: ["/run.sh"]
        args:
        - "datanode"
        env:
        - name: "JNODES_IPS"
          value: "journalnode-0.journalnode-headless.default.svc.cluster.local:8485;journalnode-1.journalnode-headless.default.svc.cluster.local:8485;journalnode-2.journalnode-headless.default.svc.cluster.local:8485"
        - name: "ZK_IP"
          value: "zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181"
        - name: "NAMENODE1"
          value: "namenode-0.namenode-headless.default.svc.cluster.local"
        - name: "NAMENODE2"
          value: "namenode-1.namenode-headless.default.svc.cluster.local"
