# Problem
# 1. run datanode by hostnetwork=true, datanode ip maybe random, not host net, ps.eth0,cni
# 2. namenode-1 will restart some times after first start, because need sync data from namenode-0
# 3. 
